from __future__ import annotations

from .assignments import (
    assignment_completion_analytics,
    create_assignment,
    evaluate_assignments_for_attempt,
    evaluate_assignments_for_attempt_ids,
    get_next_active_assignment,
    list_assignments,
    set_assignment_active,
)
from .attempts import add_question_result, create_attempt, list_attempts, mode_accuracy_by_skill
from .connection import (
    DbConfig,
    connect,
    db_config,
    get_db_config,
    managed_connection,
    override_db_config,
    reset_db_config,
    set_db_config,
)
from .historical import (
    add_exercise_candidate,
    apply_historical_answer_key,
    create_book,
    list_books,
    list_exercise_candidates,
    list_historical_questions,
    list_historical_questions_for_test,
    list_historical_tests,
    replace_historical_questions,
    upsert_historical_test,
)
from .parent_auth import (
    PIN_HASH_ITERATIONS,
    PIN_LOCK_MAX_ATTEMPTS,
    PIN_LOCK_MINUTES,
    PIN_MAX_LENGTH,
    PIN_MIN_LENGTH,
    clear_parent_lock,
    parent_pin_configured,
    parent_pin_locked,
    record_parent_auth_failure,
    set_parent_pin,
    verify_parent_pin,
)
from .profiles import create_profile, delete_profile, list_profiles
from .recoveries import add_quiz_recovery
from .progress import (
    daily_goal_status,
    list_daily_goal_history,
    list_subskill_progress,
    rebuild_subskill_progress,
    record_daily_review_completion,
    skill_progress_pipeline,
    upsert_subskill_progress,
)
from .quiz_progress import (
    clear_quiz_progress,
    clear_quiz_progress_for_profile,
    load_quiz_progress,
    save_quiz_progress,
)
from .quiz_sets import create_quiz_set, delete_quiz_set, list_quiz_sets, update_quiz_set
from .schema import init_db
from .school_year import get_school_year_target, save_school_year_target
from .summer_assessments import (
    get_summer_assessment_run,
    list_summer_assessment_runs,
    record_summer_assessment,
)
from .summer_programs import (
    archive_summer_programs,
    create_summer_program,
    get_active_summer_program,
    get_summer_program,
    list_summer_programs,
    update_summer_program,
)
from .summer_tasks import (
    create_summer_program_task,
    get_summer_program_task,
    list_summer_program_tasks,
    replace_summer_program_tasks,
    shift_summer_program_task_sequences,
    update_summer_program_task,
)
from .templates import (
    add_template_var,
    create_question_template,
    delete_template_by_external_id,
    delete_templates_by_identity,
    has_active_question_templates,
    list_all_question_templates,
    list_question_templates,
    list_template_vars,
    template_modes_for_skill,
)
from .worksheets import archive_worksheet, create_worksheet, list_worksheets

__all__ = (
    "DbConfig",
    "PIN_HASH_ITERATIONS",
    "PIN_LOCK_MAX_ATTEMPTS",
    "PIN_LOCK_MINUTES",
    "PIN_MAX_LENGTH",
    "PIN_MIN_LENGTH",
    "add_exercise_candidate",
    "add_question_result",
    "add_quiz_recovery",
    "add_template_var",
    "apply_historical_answer_key",
    "archive_summer_programs",
    "archive_worksheet",
    "assignment_completion_analytics",
    "clear_parent_lock",
    "clear_quiz_progress",
    "clear_quiz_progress_for_profile",
    "connect",
    "create_assignment",
    "create_attempt",
    "create_book",
    "create_profile",
    "create_question_template",
    "create_quiz_set",
    "create_summer_program",
    "create_summer_program_task",
    "create_worksheet",
    "daily_goal_status",
    "db_config",
    "delete_profile",
    "delete_quiz_set",
    "delete_template_by_external_id",
    "delete_templates_by_identity",
    "evaluate_assignments_for_attempt",
    "evaluate_assignments_for_attempt_ids",
    "get_active_summer_program",
    "get_db_config",
    "get_next_active_assignment",
    "get_school_year_target",
    "get_summer_assessment_run",
    "get_summer_program",
    "get_summer_program_task",
    "has_active_question_templates",
    "init_db",
    "list_all_question_templates",
    "list_assignments",
    "list_attempts",
    "list_books",
    "list_daily_goal_history",
    "list_exercise_candidates",
    "list_historical_questions",
    "list_historical_questions_for_test",
    "list_historical_tests",
    "list_profiles",
    "list_question_templates",
    "list_quiz_sets",
    "list_subskill_progress",
    "list_summer_assessment_runs",
    "list_summer_program_tasks",
    "list_summer_programs",
    "list_template_vars",
    "list_worksheets",
    "load_quiz_progress",
    "managed_connection",
    "mode_accuracy_by_skill",
    "override_db_config",
    "parent_pin_configured",
    "parent_pin_locked",
    "rebuild_subskill_progress",
    "record_daily_review_completion",
    "record_parent_auth_failure",
    "record_summer_assessment",
    "replace_historical_questions",
    "replace_summer_program_tasks",
    "reset_db_config",
    "save_quiz_progress",
    "save_school_year_target",
    "set_assignment_active",
    "set_db_config",
    "set_parent_pin",
    "shift_summer_program_task_sequences",
    "skill_progress_pipeline",
    "template_modes_for_skill",
    "update_quiz_set",
    "update_summer_program",
    "update_summer_program_task",
    "upsert_historical_test",
    "upsert_subskill_progress",
    "verify_parent_pin",
)
